census-instrumentation/opencensus-website

- content/index.md
- themes/hyde/layouts/partials/sidebar.html
Same fixes as https://github.com/census-instrumentation/census-instrumentation.github.io/pull/3 but so they get code generated
> Small website fixes

- content/index.md
And provide hyperlinks for all of them to their respective websites.
> Add SignalFx to list of supported exporters

- content/index.md
Only list backends we provide support for.
> Fix the list of exporters

- content/index.md
Added link to Google Summer of Code Ideas List.
>  Updated index.md

- content/index.md
There's a section in FAQ that says this, in more detail.
> index.md: Remove repetition of who’s behind it

- .firebaserc
- .gitignore
- config.toml
- firebase.json
Added config files for firebase hosting and https support
>  Added config files for firebase hosting and https support

- static/v2/docs.html
- static/v2/faq.html
- static/v2/index.html
- static/v2/roadmap.html
index.html - added erlang button to language list on page.
docs.html - added package link to to Erlang card on page.
faq.html & roadmap.html - updated the exporter table to include prometheus, zipkin & stackdriver for erlang
> March15 - modified index.html, faq.html, docs.html, roadmap.html

- static/v2/roadmap.html
> Update Java and C++ exporter progress.

- static/v2/roadmap.html
- Mark C++ Zipkin exporter as done (per https://github.com/census-instrumentation/opencensus-cpp/pull/139).
- Add [Instana exporter](https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/trace/instana#opencensus-instana-trace-exporter).
> Update progress on exporters

- static/v2/about.html
- static/v2/blog.html
- static/v2/community.html
- static/v2/cpp.html
- static/v2/css/style.css
- static/v2/docs.html
- static/v2/dotnet.html
- static/v2/erlang.html
- static/v2/faq.html
- static/v2/glossary.html
- static/v2/go.html
- static/v2/guides.html
- static/v2/index.html
- static/v2/java.html
- static/v2/nodejs.html
- static/v2/overview.html
- static/v2/php.html
- static/v2/python.html
- static/v2/quickstart.html
- static/v2/reference.html
- static/v2/roadmap.html
- static/v2/ruby.html
- static/v2/spanner.html
- static/v2/stats.html
- static/v2/tags.html
- static/v2/trace.html
- static/v2/webjs.html
> Friday, April 13

- static/v2/about.html
- static/v2/blog.html
- static/v2/community.html
- static/v2/cpp.html
- static/v2/docs.html
- static/v2/dotnet.html
- static/v2/erlang.html
- static/v2/faq.html
- static/v2/glossary.html
- static/v2/go.html
- static/v2/guides.html
- static/v2/java.html
- static/v2/nodejs.html
- static/v2/overview.html
- static/v2/php.html
- static/v2/python.html
- static/v2/quickstart.html
- static/v2/reference.html
- static/v2/roadmap.html
- static/v2/ruby.html
- static/v2/spanner.html
- static/v2/stats.html
- static/v2/tags.html
- static/v2/trace.html
- static/v2/webjs.html
New blog entries and some mobile friendly edits
> April 19 - 

- .travis.yml
And disable hugo until the website becomes a hugo website again.
> Don't push to GitHub pages

- firebase.json
Error: https://travis-ci.org/census-instrumentation/opencensus-website/jobs/368791724#L1016
Context: https://github.com/census-instrumentation/opencensus-website/pull/59#issuecomment-382875196
> Push to firebase from static/v2

- static/v2/blog.html
> Updated blog

- AUTHORS
- LICENSE
LICENSE + AUTHORS has been added to the directory.
> LICENSE + AUTHORS added

- static/v2/blog.html
Three new entries for May 13th, 7th and 4th.
> Updated blog posts

- content/cpp.md
Just some cosmetic changes to make the documentation a bit more readable.
> Fix up some documentation

- content/docs.md
- content/faq.md
- content/roadmap.md
- static/css/style.css
Fix - <tables> where previously not rendering properly on mobile.
> Optimizing Docs, FAQ & Roadmap pages for mobile

- content/index.md
- layouts/partials/index_nav.html
- static/css/style.css
This fixes rendering bugs on landing page
> Thinned out navbar & shrunk banner height on landing

- content/blog.md
- static/css/style.css
Added new blog entry, and a few lines into CSS to help cosmetically.
> New Blog entry & some CSS to help

- content/blog.md
- content/overview.md
Added the new blog entry by Nike's Principal Engineer - Nic Munroe to the Overview page via link, and regular blog entry on Blog page.
> added new blog entry, and link to the same blog on the overview page

- content/about.md
- content/index.md
Added Repkins' quote below the index banner.
Removed the last sentence in the About page's - Who is behind OpenCensus
> Added Ben Ripkens quote to top of Index

- content/index.md
> Dropped Ben Ripkens name down to new line

- content/overview.md
This link should be linked later in the blog.
Fixes #100.
> Remove irrelevant link

- layouts/partials/footer.html
- layouts/partials/index_footer.html
> Remove unused community pages

- content/docs.md
- content/index.md
- content/overview.md
- content/quickstart.md
- content/roadmap.md
- layouts/partials/footer.html
- layouts/partials/index_footer.html
- layouts/partials/index_nav.html
- layouts/partials/nav.html
- themes/census/layouts/shortcodes/sc_cpp.html
- themes/census/layouts/shortcodes/sc_erlang.html
- themes/census/layouts/shortcodes/sc_go.html
- themes/census/layouts/shortcodes/sc_java.html
- themes/census/layouts/shortcodes/sc_overview.html
- themes/census/layouts/shortcodes/sc_php.html
- themes/census/layouts/shortcodes/sc_python.html
- themes/census/layouts/shortcodes/sc_ruby.html
- themes/census/layouts/shortcodes/sc_stats.html
- themes/census/layouts/shortcodes/sc_tags.html
- themes/census/layouts/shortcodes/sc_trace.html
index.html doesn't exist anymore. Also use absolute links everywhere,
so the links don't get affected if the page moves.
> Fix links to the non-existing pages

- content/community.md
- content/cpp.md
- content/docs.md
- content/erlang.md
- content/glossary.md
- content/go.md
- content/gogrpc.md
- content/java.md
- content/overview.md
- content/php.md
- content/python.md
- content/quickstart.md
- content/reference.md
- content/roadmap.md
- content/ruby.md
- content/stats.md
- content/tags.md
- content/trace.md
- static/css/style.css
- themes/census/layouts/_default/single.html
- themes/census/layouts/shortcodes/sc_ulist.html
> Remove inline HTML

- content/faq.md
> Flatten the FAQ

- content/about.md
- content/community.md
- content/docs.md
- content/erlang.md
- content/go.md
- content/gogrpc.md
- content/java.md
- content/overview.md
- content/php.md
- content/python.md
- content/roadmap.md
- content/ruby.md
- static/css/style.css
- themes/census/layouts/shortcodes/sc_supportedLanguages.html
>  Remove the inline styling, automatically style links

- content/faq.md
The rest of the page uses unordered lists, be consistent in this
section as well.
> Use consistent listing style

- content/docs.md
- layouts/partials/footer.html
- layouts/partials/index_nav.html
- themes/census/layouts/_default/single.html
- themes/census/layouts/shortcodes/sc_supportedLanguages.html
It is not good practice to set a _blank target.
We should always honor user's preferences.
Users know how to open in a new tab if required.
Fixes #113.
> Honor user's target

- content/index.md
* Overview is linking to a video asset instead of the /overview page.
* Fix wording where we call for contributions.
* Use roadmap consistently everywhere.
> Improvements to the homepage

- content/roadmap.md
This is a journey ahead on platforms and languages.
> Fix typo on the roadmap page

- content/erlang.md
- content/gogrpc.md
- static/css/style.css
- themes/census/layouts/shortcodes/sc_code.html
Use markdown code escape instead.
Fixes #125.
> Remove the necessity to have sc_code

- content/stats.md
- content/tags.md
- content/trace.md
- themes/census/layouts/_default/single.html
To make them more visible and accessible.
> Add conceptual docs to the left navigation

- content/glossary.md
Various fixes to improve misleading/inaccurate definitions.
Some editorial improvements as well.
Fixes #136.
> Fix glossary

- themes/census/layouts/shortcodes/sc_supportedLanguages.html
Also reorder the tracing and stats colums.
On the website we always follow stats, tracing order.
> Add C# to the roadmap

- layouts/partials/footer.html
> Add Google Analytics tracking code

- content/blog.md
- static/css/style.css
Also remove the unnecessary metadata and
target=_blank.
> Fix the excessive whitespace around blog items

- content/blog.md
> Replaced markup with markdown in blog.md

- content/exporters.md
- static/css/style.css
- static/js/main.js
- themes/census/layouts/_default/single.html
- themes/census/layouts/shortcodes/go.html
- themes/census/layouts/shortcodes/java.html
- themes/census/layouts/shortcodes/snippets.html
Also add a mechanism that allows us
to provide language snippets in tabs.
> Add the exporters page

- content/overview.md
- content/traces.md
- layouts/partials/contribute.html
- static/css/style.css
- themes/census/layouts/_default/single.html
PR also includes some markup and content cleanup.
> Move distracting edit on Github link to the bottom

- content/integrations/google_cloud_storage/Go.md
Ensure that we register trace and stats exporters.
> content/integration/gcs: commit uncommitted exporter enablement

- content/quickstart/go/metrics.md
- content/quickstart/go/tracing.md
- content/quickstart/java/metrics.md
- content/quickstart/java/tracing.md
- content/quickstart/python/metrics.md
- content/quickstart/python/tracing.md
> Correct various grammar & whitespace issues

- content/users/_index.md
> Add users page

- content/blogs/_index.md
- content/blogs/iot.md
* Affix the various `shell` code identifier to shell code
* Affix the JSON code identifier to JSON code
as well as appropriately quote and delimit its fields
* Remove the class "resized-logo" to ensure the images
are full-sized
* A space between `Filter` and method
* "Google, Inc" --> "Google, LLC"
> content/blogs: update iot.md with style edits

- content/blogs/_index.md
> Update Blogs index.

- content/quickstart/java/tracing.md
Using the knowledge gained from #251 and #264, I have cleaned up the Java Traces Quickstart.
This PR does the following:
* More eloquent installation section
* Squash non-instrumentation code changes in to first step
* Fixed errors that lead to broken compilations
* More verbose "Getting Started"
* Removed unneeded "Step 1" and "Step 2" code comments
* Instruct the user where to insert the code snippets
> content/quickstart: Cleanup Java Traces Quickstart

- content/guides/gRPC/Python.md
> content/guides/gRPC: s/AlwaysSampler/AlwaysOnSampler/g

- content/guides/exporters/custom-exporter/Node.js/Metrics.md
- content/guides/exporters/custom-exporter/Node.js/_index.md
- content/guides/exporters/custom-exporter/_index.md
- content/guides/exporters/supported-exporters/Node.js/_index.md
- content/guides/exporters/supported-exporters/Node.js/stackdriver-stats.md
- content/guides/exporters/supported-exporters/Node.js/stackdriver-trace.md
- content/guides/exporters/supported-exporters/_index.md
- content/language-support/_index.md
Addresses the stalled feedback from PR #261 for
semantic/typographic corrections. A bunch of the code
though still needs instructions on how to compile/generate
it, the right dependencies and pictures of traces.
> content/*: fix Node.js submission typos and formatting

- layouts/codelabs/googlecloudstorage.html
- layouts/codelabs/jaeger.html
- layouts/codelabs/prometheus.html
- layouts/codelabs/spanner.html
- layouts/codelabs/stackdriver.html
- layouts/codelabs/zipkin.html
- layouts/partials/custom-footer.html
Requested offline
Replaces old Google Analytics in `custom-footer.html` and also adds it to all of the codelabs.
/cc @odeke-em
> Add new Google Analytics

- content/blogs/_index.md
> Remove entries that are found in /guides

- content/quickstart/java/metrics.md
- content/quickstart/java/tracing.md
- add missing maven update command in metrics.md and tracing.md
- Fixes #350
> quickstart/Java: add missing maven update command

- content/guides/integrations/sql/java_sql.md
DO NOT MERGE before we made the v0.0.2 release.
> Update dependency for ocjdbc.

- content/articles/ms-ignite-2018.md
> Blog: Remove the duplicated title.

- layouts/shortcodes/feature-matrix.html
- layouts/shortcodes/languages.html
I think the Python `Stats` module, `Stackdriver Stats Exporter` and `Prometheus Stats Exporter` are done.
> content/languages: Update Python progress.

- layouts/shortcodes/feature-matrix.html
- layouts/shortcodes/languages.html
Fixes https://github.com/census-instrumentation/opencensus-website/issues/379.
/cc @SergeyKanzhelev @simonz130
> content/languages & feature-matrix: Update C# progress.

- layouts/shortcodes/feature-matrix.html
Prometheus and Stackdriver stats exporters.
> content/feature-matrix: update Node.js exporters.

- content/guides/exporters/supported-exporters/Go/XRay.md
> Update the import path used in AWS X-ray Go examples

- content/guides/exporters/supported-exporters/Node.js/Jaeger.md
> Add missing parameter in docs embedded code

- content/_index.md
- content/guides/exporters/supported-exporters/Go/ApplicationInsights.md
- content/guides/exporters/supported-exporters/Go/_index.md
- content/guides/exporters/supported-exporters/Python/ApplicationInsights.md
- content/guides/exporters/supported-exporters/Python/_index.md
- layouts/shortcodes/feature-matrix.html
Adding a footprint for Microsoft Azure Monitor (aka Application Insights) documentation to the website.
> Microsoft Azure Monitor doc footprint

- content/quickstart/cpp/metrics.md
Fix some embarrasing typos in the metrics section
that somehow crept in despite even a grep for "tracing"
> quickstart/c++: fix metrics typos

- content/quickstart/cpp/metrics.md
- Don't statically initialize Measures, in order to avoid initialization
order problems. (this isn't a problem in the example but we want to
set a good example for people to copy)
- Register two measures at once, it's more efficient.
> Update metrics code and build.

- content/quickstart/cpp/metrics.md
- content/quickstart/go/metrics.md
- content/quickstart/go/tracing.md
- content/quickstart/java/metrics.md
- content/quickstart/java/tracing.md
- content/quickstart/nodejs/metrics.md
- content/quickstart/nodejs/tracing.md
- content/quickstart/python/metrics.md
- content/quickstart/python/tracing.md
Sorry for being pedantic, but after reading through a couple of the quickstarts, I couldn't leave this alone. "gleam" means to shine or shimmer. "glean" means to collect or extract information. I think you mean to say the latter here.
> I think you mean "glean"

- content/exporters/supported-exporters/Node.js/Instana.md
- content/exporters/supported-exporters/Node.js/Jaeger.md
- content/exporters/supported-exporters/Node.js/Prometheus.md
- content/exporters/supported-exporters/Node.js/Zipkin.md
- content/exporters/supported-exporters/Node.js/_index.md
- content/exporters/supported-exporters/Node.js/stackdriver-stats.md
- content/exporters/supported-exporters/Node.js/stackdriver-trace.md
- content/exporters/supported-exporters/Python/ApplicationInsights.md
- content/exporters/supported-exporters/Python/Jaeger.md
- content/exporters/supported-exporters/Python/Stackdriver.md
- content/exporters/supported-exporters/Python/Zipkin.md
- content/exporters/supported-exporters/Python/_index.md
> exporters/supported-exporters/{Node.js, Python}: update URL aliases

- content/language-support/_index.md
Add csharp library link to language support page.
> Add csharp to language support list

- content/_index.md
Follow-up of PR #432
Fixes #444
> content/_index.md: /introduction/overview -> /introduction/#overview

- content/exporters/supported-exporters/Go/Honeycomb.md
> fix broken link

- content/community/_index.md
> Added link to code of conduct for OC community

- content/tracing/span/link.md
Included are link code samples for Go, Java, Python, and Node.
I verified the creation of links for each client library through the usage of their own respective print/console exporters.
I am still working on understanding Bazel's BUILD file to finish the C++ snippet.
> Link code samples

- content/stats/measure.md
- content/stats/view.md
- content/tracing/sampling/always.md
- content/tracing/sampling/never.md
- content/tracing/sampling/probabilistic.md
- content/tracing/span/kind.md
- content/tracing/span/link.md
- content/tracing/span/name.md
- content/tracing/span/status.md
- content/tracing/span/time_events/annotation.md
- content/tracing/span/time_events/message_event.md
> Add Node.js code samples to Stats and Tracing

- content/quickstart/go/metrics.md
- content/quickstart/java/metrics.md
- content/quickstart/nodejs/metrics.md
- content/quickstart/python/metrics.md
> Calculate "Lines In" with an aggregate of "Line Lengths"

- content/guides/gRPC/Java.md
cc: @odeke-em 
I made a first pass.  The main thing I think needs to be updated is error handling.  I made a few changes as a pattern, but I wanted to make sure you are okay with it before doing all of them.  The main thing is to either handle the error, or let it propagate.  This means declaring a thrown exception, or else handling in said function. 
Also I made some minor spelling checks.   Several of the sentences don't read quite right, though I don't quite know what the sentiment should be.  For example:
> We'll instrument the client too by tracing as well as gRPC metrics using OpenCensus with imports such as:
I think this is is trying to say that both tracing and metrics are included.  If you read this aloud, it doesn't flow quite right.  Not sure what a better way would be though.
> guides/grpc: make some changes to the Java tutorial

- content/tag/key.md
- content/tag/map.md
- content/tag/value.md
Fixes https://github.com/census-instrumentation/opencensus-website/issues/488
> Update C++ tagging examples.

- layouts/shortcodes/feature-matrix.html
Integration available at https://github.com/opencensus-beam/datadog
> Add DataDog integration information

- content/tracing/span/time_events/_index.md
> tracing/span: Correct sentence phrasing

- content/stats/measure.md
- Add line break in table for wrapping linked text
> Stats/Metrics: Add line break for wrapping the linked text

- content/tracing/span/parentspanid.md
- fix phrasing in description of ParentSpanID
- fixes #501
> Tracing/Span : Fix ParentSpanID description

- content/tracing/span/time.md
> Tracing/Span: Add Span Lifetime description

- content/tracing/sampling/always.md
- content/tracing/sampling/never.md
- content/tracing/sampling/probabilistic.md
- fixes #516 
@odeke-em please review!
> Tracing/Sampling: Add Python code for Sampling

- content/guides/integrations/google_cloud/google_cloud_spanner/Go.md
Changed package for Stackdriver exporter, added go get commands, and …
> Changes to Google Cloud Spanner integration guide

- layouts/shortcodes/feature-matrix.html
https://github.com/census-instrumentation/opencensus-java/pull/1652.
> content/feature-matrix: add Java Datadog Tracing exporter.

- codelabs/javasqlguide/codelab.json
- layouts/codelabs/javasqlguide.html
> Codelabs/Java SQL guide: Fix updated changes to ocjdbc

- content/language-support/_index.md
> Fix for Issue 534

- content/quickstart/dotnet/tracing.md
- Remove errant back-ticks
- Correct git clone URL
> Copyediting

- content/guides/integrations/google_cloud/google_cloud_bigtable/Java/_index.md
* Modernize Google Cloud Bigtable dependencies
but also to ensure things compile without failing
at runtime with gRPC and Netty dependency
* Also ran ./gradlew goJF on the source code
> guides: modernize Google Bigtable Java dependencies

- content/feature_matrix/_index.md
> Publish feature matrix

- content/tracing/span/time_events/annotation.md
Annotation.fromDescription does not take attribute, it must be fromDescriptionAndAttributes.
> Fix addAnotation in java

- content/feature_matrix/_index.md
Use -> https://github.com/census-instrumentation/opencensus-website/pull/567/files?short_path=e757fd0#diff-e757fd00efb541466331df53060df894 to see visual modification.
> Feature matrix update 1

- content/feature_matrix/_index.md
Tracing page after this change:
/cc @c24t @dinooliva @rghetia
> feature-matrix: complete the matrix and add sub-titles.

- content/feature_matrix/_index.md
This adds details to the feature matrix wrt OpenCensus PHP Tracing. 
Closes #570.
> feature matrix update for PHP

- content/exporters/supported-exporters/Go/ocagent.md
> exporters: document ocagent for Go

- content/agent/receivers/_index.md
- content/agent/receivers/zipkin/_index.md
Started the "receivers" section and firstly added
"Zipkin".
Updates #560
> agent/receivers: start section and add Zipkin

- content/agent/receivers/opencensus/_index.md
Add section about the OpenCensus receiver.
Updates #560
> agent/receivers: add OpenCensus

- content/agent/receivers/jaeger/_index.md
Add section about the Jaeger receiver.
Updates #560
> agent/receivers: add Jaeger

- content/agent/receivers/prometheus/_index.md
Add section about Prometheus receiver.
Updates #560
> agent/receivers: add Prometheus

- content/agent/_index.md
> Agent: fix ambiguity in "backend providers"

- codelabs/gosqlguide.md
- codelabs/gosqlguide/index.html
- content/agent/exporters/jaeger/_index.md
- content/exporters/supported-exporters/Go/Jaeger.md
- layouts/codelabs/gosqlguide.html
Should fix all Jaeger collector_endpoint URLs. 
fixes #602 
@odeke-em
> All: Fix all Jaeger collector_endpoint URLs

- content/exporters/custom-exporter/Java/Metrics.md
Partially addresses 
https://github.com/census-instrumentation/opencensus-website/issues/561
> Added example of metrics custom exporter for Java

- content/tracing/span/time_events/message_event.md
> Tracing/Span: Add Node.js code for MessageEvents

- content/guides/gRPC/Nodejs.md
Will include detailed example later similar to https://opencensus.io/guides/grpc/java/
> Guides/gRPC: Nodejs example

- content/guides/http/java/jetty/client.md
Typo in ToC s/Extracing observability/Extracting observability/
> Typo in Jetty client integration guide

- content/feature_matrix/_index.md
> add c# in features

- content/quickstart/java/tracing.md
Fixed three bad links and a mistake in a change directory command.
> Fixed bad links in Java Tracing quickstart

- content/feature_matrix/_index.md
> content: Update Feature Matrix 3/4.

- layouts/shortcodes/feature-matrix.html
Related to https://github.com/census-instrumentation/opencensus-java/pull/1774.
> layout: add Elasticsearch Trace exporters.

- content/feature_matrix/_index.md
Per our meeting yesterday, Counter and Cumulative APIs should also be part of the feature parity effort.
> feature-matrix: add Cumulative APIs.

- content/exporters/supported-exporters/Java/ocagent.md
Fixes https://github.com/census-instrumentation/opencensus-website/issues/561.
> exporter/java: Add OcAgent exporter tutorial.

- content/feature_matrix/_index.md
Add Ruby column based on the current Ruby columns in the internal spreadsheet.
> Add Ruby column to feature matrix

- content/blogs/_index.md
CC: @mtwo @flands 
@mtwo, do you know if slides will be published?
> update on next 2019

- content/blogs/_index.md
See https://github.com/census-instrumentation/opencensus-website/pull/668#issuecomment-483484752.
> blogs: add a link to Next slides.

- layouts/shortcodes/feature-matrix.html
> Updated SignalFx support

- content/exporters/_index.md
This nice simplification of the description of an
exporter is adapted from a suggestion by @sanjaypujare.
Fixes #693
> content/exporters: simplify introduction

- content/_index.md
- static/css/header.css
- themes/docdock/layouts/partials/flex/body-beforecontent.html
Replaced the survey link with a link to OpenTelemetry.io and added a note to the homepage
> Add links to OpenTelemetry

- codelabs/gosqlguide.md
- codelabs/gosqlguide/index.html
- content/articles/iot.md
- content/community/_index.md
- content/exporters/custom-exporter/Node.js/Metrics.md
- content/exporters/custom-exporter/Node.js/Trace.md
- content/feature_matrix/_index.md
- content/guides/http/_index.md
- content/integrations/caddy.md
- content/integrations/dropwizard.md
- content/integrations/memcached/Go.md
- content/integrations/memcached/Java/spymemcached.md
- content/integrations/sql/go_sql.md
- content/quickstart/erlang/metrics.md
- content/quickstart/erlang/tracing.md
- content/quickstart/nodejs/metrics.md
- content/tracing/span/spanid.md
- content/tracing/span/time_events/annotation.md
- content/tracing/span/tracestate.md
- layouts/codelabs/gosqlguide.html
Changes are generated with
$ misspell -w .
See https://github.com/client9/misspell
> Fix all typos

- content/exporters/supported-exporters/Go/Stackdriver.md
- content/integrations/google_cloud/google_cloud_bigtable/Go/_index.md
- content/integrations/google_cloud/google_cloud_spanner/Go.md
- content/integrations/memcached/Go.md
- content/integrations/mongodb/go_driver.md
- content/integrations/redis/Go/gomodule_redigo.md
- remove StopMetricsExporter from non-main func.
> update more example to use StartMetricsExporter

- content/_index.md
- content/feature_matrix/_index.md
- layouts/shortcodes/feature-matrix.html
Changed Stackdriver to Google Cloud Monitoring + Trace
> Stackdriver rebrand

- content/quickstart/cpp/metrics.md
- content/stats/view.md
- register views without creating unnecessary View instance
- line count refers to line lengths, not latency
- fix WORKSPACE for newer Bazel & prometheus-cpp
> Clean up C++ quickstart.

- content/integrations/azure/_index.md
- static/images/azure.svg
Creating the first page about azure integration
> Creating the first page about azure integration

- content/quickstart/go/metrics.md
Add a missing startTime in example allowing the full example to be compilable
> Add missing startTime in example

- content/exporters/supported-exporters/Go/Stackdriver.md
> Update Stackdriver minimum stats reporting period
