config.toml

Still pointing to the test URL, switch to the opencensus.io domain.

Fix the base URL

---

themes/hyde/layouts/_default/baseof.html
themes/hyde/layouts/partials/sidebar.html
themes/hyde/static/css/hyde.css

Moved the fork for the website into the content and made the sidebar link point to the GitHub Org in response to: https://github.com/census-instrumentation/opencensus-website/pull/10#discussion_r146655203

Change the website forking info

---

content/index.md

Reading the introduction on the homepage, I noticed that a paragraph occured twice.
I don't know if that was on purpose, but it was a bit irritating. Therefore, I suggest removing the second occurence as it does not add any additional value.
Alternatively, we should also link to Github in the paragraph I deleted, just as we do in the first paragraph. 😉

Avoid duplicate paragraph in docs

---

static/v2/docs.html
static/v2/reference.html

Adds links to the API reference documentation from the docs page. Also updated the Java API reference docs to point at javadoc.io rendered version.

Link to API ref docs from docs page, update javadoc URL

---

.travis.yml

If we go down the path of embedding the auto-generated API docs directly into opencensus.io, we can use add a simple script per-language to download and unzip the content from a github archine. Each language would be responsible for maintaining their own docs in their gh-pages branch (or another well-known branch such as "docs").
cc @tags07

Pull language docs into static site prior to deployment

---

static/v2/erlang.html

It seems the copy is missing `]}`. 
The example repo has the correct number of brackets and curly braces - https://github.com/census-instrumentation/opencensus-erlang/blob/5a066bced2c2f6550cb8080fed956d1f93206d8a/examples/helloworld/config/sys.config

Add missing bracket and curly brace

---

content/index.md

Fix a minor typo
"HOW IS BEHIND OPENCENSUS"
to
"WHO IS BEHIND OPENCENSUS"
Fixes #77

Fix typo "HOW" to "WHO"

---

README.md
layouts/partials/footer.html
layouts/partials/index_footer.html
themes/census/README.md

I have updated README for Hugo version control. We are working on fixing this, so the site builds on the current version of Hugo (which it currently will not). Tutorials will point to spanner/ at this time. Once we have a couple more tutorials, we will collect them into a stand-alone tutorials/ page.

Updated README Hugo version and pointing tutorials link to spanner

---

content/overview.md

Simply moved the blog link from bottom to top of Overview page.

Shifted Nic Munroe blog link to top of Overview page

---

content/roadmap.md
static/css/style.css
themes/census/layouts/shortcodes/sc_statsExporter.html
themes/census/layouts/shortcodes/sc_traceExporter.html

I wanted to get an idea about OpenCensus' support matrix is. While doing
so, I discovered that the roadmap documentation is outdated. This PR
updates the roadmap document. To do so, I went through all the
OpenCensus repos to get an idea what the exporters actually support
(many only support either stats or traces).
- add Node.js as supported language
- sort languages and exporters alphabetically
- update exporter support matrix
- document PHP, Node.js and Ruby exporter support
- clearly differentiate between trace and stats support of exporters
This is what the support matrix looks like with this PR (tooltip being used to explain badges, mouse cursor not visible in screenshot):

Update list of supported languages and exporters

---

content/faq.md
content/roadmap.md
layouts/partials/statsExporter.html
layouts/partials/traceExporter.html
themes/census/layouts/shortcodes/sc_statsExporter.html
themes/census/layouts/shortcodes/sc_supportedExporters.html
themes/census/layouts/shortcodes/sc_supportedLanguages.html
themes/census/layouts/shortcodes/sc_traceExporter.html

I noticed that the supported languages and exporters are also listed within the FAQ section (my previous PR only updated the roadmap file). This PR…
- lists Instana and Jaeger Node.js exporters as supported
- ensures that roadmap and FAQ refer to the same support tables (via shortcode/partials)

Update and ensure language & exporter list consistency

---

static/css/style.css

Open Sans is more optimized for titles and makes it harder
to read the regular text.
Use Arial and other sans-serif fonts for the regular text.
Fixes #110.

Use Arial for regular text

---

layouts/partials/index_nav.html
layouts/partials/nav.html

I have seen multiple users finding it hard to find a link
to our GitHub organization. Add a link to the top nav
to make it more visible.
Fixes #111.

Add GitHub to the top navigation

---

content/docs.md
layouts/partials/index_nav.html
layouts/partials/nav.html

Navigation bar is now overflowing due to the addition
of GitHub and font change.
Move glossary link to the /docs and remove it from
the top navigation.

Don't make the navigation bar overflow

---

content/faq.md

Until we have a guide.
Fixes #135.

Remove "How do I integrate OpenCensus with my framework?"

---

static/css/style.css

Paragraphs and list items have different settings for line height
and margin/padding. Make them consistent.

Make the whitespace around list items compatible to the regular text

---

content/docs.md
content/go.md
static/css/style.css

* Have more focus on the gRPC/HTTP integrations.
* Show how to use the low-level APIs for custom instrumentation.
* Mention exporters.
* Add link to the GitHub repo.
Fixes #159.

Revise the Go quickstart

---

content/docs.md

Specific versions should not be included in the url. "https://www.javadoc.io/doc/io.opencensus/opencensus-api/" will just navigate to the latest version.

Fix the link to javadoc.io

---

content/stats.md

Latency was spelled wrong in the example.

Fix typo in stats.md

---

content/_index.md
content/integrations/redis/Java.md

* Re-phrase some wording to make rhetorical questions
more actionable such as from:
"Can I use OpenCensus in my project?"
to
"How can I use OpenCensus in my project"
* Add buttons to links that add visibility to resources such as
Gitter and Github
* Update wording from:
"What are Metrics and Tracing?"
to
"What are Metrics and Traces?"
because the explanation in the sub-text uses
"Traces" instead of "Tracing"
* Add information for how users can contribute to OpenCensus. This
perhaps will encourage more involvement and inclusion
* Add links for viewing traces and metrics in
content/integration/redis/Java
All the above are suggestions from core users via offline discussions.

content: update wording from offline suggestions

---

content/_index.md

Moves homepage buttons in to a relevant section and potentially fixes the below issue:

content/_index: move buttons to relevant section. Also addresses #200

---

content/integrations/google_cloud_storage/Go.md
content/quickstart/java/metrics.md
content/quickstart/java/tracing.md
content/supported-exporters/Java/Instana.md
content/supported-exporters/Java/Jaeger.md
content/supported-exporters/Java/Prometheus.md
content/supported-exporters/Java/SignalFx.md
content/supported-exporters/Java/Stackdriver.md
content/supported-exporters/Java/Zipkin.md

* Update Java OpenCensus version from 0.14.0 to 0.15.0
which is the latest
* In content/integrations/google_cloud_storage, go fmt
the Go snippet as it mixed tabs with spaces
Thanks to @songy23 for the offline feedback!

content/*: update Java OC version to 0.15.0 from 0.14.0

---

content/quickstart/java/metrics.md
content/quickstart/java/tracing.md

1. Use all upper cases for constant names (`Measure`, `TagKey`);
2. `Tagger`, `Tracer` and `StatsRecorder` are not constants since they are mutable. Use camel cases for them.

Update variable names in Java quickstart.

---

content/custom_exporter/Java/Trace.md
content/custom_exporter/Java/_index.md

Updates #216
Provided a guide and runnable custom trace exporters.
Metrics exporters don't conform to an interface in Java
but use a pull model which will be handled instead by
the Java implementation team hence will follow in a
separate change.

content: add writing a custom Trace exporter in Java

---

content/introduction/overview.md

https://opencensus.io/docs/ has been removed.

Fix a doc link in Overview.

---

static/css/content.css

Fixes #235 
This PR does two things:
1. Removes `overflow: scroll` for all `td` elements
2. Applies `white-space: nowrap` to `code` and `a` elements.
Scenarios:
The website's usage of table cells currently compose of these items:
*  Explanatory text
* URL
* Code snippet
This PR's styling guide operates under the following framework:
The contents of an *explanatory text* is immediately informative to the eye and thus is granted the ability to take up multiple lines.
The contents of a *URL*  is not important to the eye. The only thing that may be of interest to the user is the ability to see the root domain, but it is not relevant. This should only be on one line (`white-space: nowrap`) and scrollable (`overflow: scroll`).
The contents of a *code snippet*, while potentially important at a …

Remove unneeded scrollbars on tables

---

content/quickstart/go/metrics.md

Reported offline via email by Bala Chandrasekaran:
* Missing Name field for MLineLengthView which would
confusingly put metrics under "repl/*" instead of "demo/"
* Add `-v` to `go get` steps since installing packages for
the first time takes forever giving an impression of a
hanging installation. I've also added `-u` to ensure that
users always have the latest packages

content/quickstart: update Go metrics quickstart

---

content/guides/exporters/supported-exporters/Go/Jaeger.md
content/guides/exporters/supported-exporters/Go/Prometheus.md
content/guides/exporters/supported-exporters/Go/Stackdriver.md
content/guides/exporters/supported-exporters/Go/Zipkin.md
content/guides/exporters/supported-exporters/Java/Jaeger.md
content/guides/exporters/supported-exporters/Java/Prometheus.md
content/guides/exporters/supported-exporters/Java/SignalFx.md
content/guides/exporters/supported-exporters/Java/Stackdriver.md
content/guides/exporters/supported-exporters/Python/Jaeger.md
content/guides/exporters/supported-exporters/Python/Stackdriver.md
content/guides/exporters/supported-exporters/Python/Zipkin.md
content/guides/gRPC/Go.md
content/guides/gRPC/Java.md
content/guides/gRPC/Python.md
content/guides/integrations/redis/Java.md
content/quickstart/go/metrics.md
content/quickstart/go/tracing.md
content/quickstart/java/metrics.md
content/quickstart/java/tracing.md
content/quickstart/python/metrics.md
content/quickstart/python/tracing.md

Fixes #247 
Two changes made:
* Position of the notice
* Color of the notice
Sections that were changed:
* quickstarts
* guides/exporters/supported-exporters
* guides/grpc
* guides/integrations/redis
**Why position change?** By placing the notice either at the end of an overview or installation section, the user's eye is already slowly moving while they read thus giving them a higher chance of not glancing over the notice. In its original position at the top of the page, I believe that the user's eye is quickly moving to find the table of contents and will gloss over the notice.
**Why the color change?** This is more subjective. I think that the green and red pop out more.
Some previews:

More attention grabbing notes

---

content/quickstart/go/metrics.md
content/quickstart/java/metrics.md
content/quickstart/java/tracing.md

Reported offline by Mayur Kale, a bunch of URLs linked
to `http://localhost:1313/` which is wrong. We want relative
URLs that are agnostic of host and automatically resolve
so are of the prefix `/`.

content: remove all vestiges of localhost:1313 absolute URLs

---

content/quickstart/python/metrics.md
content/quickstart/python/tracing.md

Reported offline Mayur Kale, the Python installation code
needs to also install:
* google-cloud-monitoring for Metrics
* google-cloud-trace for Tracing
Henry Ventura also independently discovered and reported
offline then used in the gRPC for Python tutorial submission
in PR #239

content/quickstart/python: google-cloud-{monitoring, trace} deps

---

content/quickstart/go/metrics.md
content/quickstart/go/tracing.md
content/quickstart/java/tracing.md
content/quickstart/python/metrics.md
content/quickstart/python/tracing.md

Reported offline by Mayur Kale, most of the "Requirements"
were broken. Accidentally they had been set to "#background".
I confirmed this by
```shell
$ grep -Rn '\[Requirements' *
```
and inspecting the returned results.

content/quickstart: update Requirements links

---

content/quickstart/java/metrics.md

This PR is a response to offline feedback and addresses the following:
**Removes code changes in "Getting Started"**
This allows all code changes in the tutorial to be for instrumentation. The code change in "Getting Started" has been squashed into "Installation", thus removing a step for the user.
**Expanded Instructions**
Some explicit instructions were added to inform the user to change in to certain directories and remove the unneeded test file.
**Misc. Word Changes**
Create Metrics/Tags -> Declare Metrics/Tags
Instructing where to insert code snippets
More concise and verbose wording
**Added Missing Code Snippet**
There was a missing code snippet towards the end for `envOrAlternative`.
**Example Clarification**
The quickstart illustrates an example by creating an unused variable …

content/quickstart: Make Java Metrics more verbose and concise

---

content/quickstart/go/metrics.md

content/quickstart: add missing "io" import in first snippet

---

content/quickstart/java/metrics.md

Implements request made [here](https://github.com/census-instrumentation/opencensus-website/pull/251#discussion_r211420780)
* Replaces `mvn archetype:generate` with a few simple commands
* User stays in project root directory

content/quickstart: More Eloquent Java Metrics Installation

---

content/quickstart/go/metrics.md

Setting the reporting period to 2 seconds seems to cause
Stackdriver to return an error some of the time about time series
being written too frequently.

Remove SetReportingPeriod from examples

---

content/quickstart/python/metrics.md

Fixes #260 
This PR does the following:
* Changes to Table of Contents to match article structure
* Added `--upgrade` to pip command because `opencensus.stats` only recently became available
* Adjusts first code snippet to make the application run
* Removes Stackdriver screenshots because metrics exporter does not exist
* Adds second warning at end of quickstart that metrics exporter does not exist
Table of Contents
Second Warning

content/quickstart: Python Metrics clean up

---

content/quickstart/java/metrics.md
static/css/content.css

Fixes #267
This PR allows us to standardize the usage of headings across all guides to create more consistency. It also makes the Table of Contents more visually digestable.
Included in this PR:
* style changes in content.css
* refactor of java metric quickstart to incorporate new style standard
If this PR is agreeable, I will follow up shortly with another PR that incorporates the new style standard across all guides.
Images: 
* [Previous Headings](https://user-images.githubusercontent.com/5974764/44432913-e7d4fb00-a558-11e8-9e18-93acaba18384.png) | [New Headings](https://user-images.githubusercontent.com/5974764/44432918-ec011880-a558-11e8-92df-fdb535e83a62.png)
* [Table of Contents](https://user-images.githubusercontent.com/5974764/44480242-9e87b880-a5f7-11e8-8f68-d648628a2e70.png)
* …

Restyle Headings and Table of Contents

---

content/quickstart/node.js/_index.md
content/quickstart/node.js/tracing.md
layouts/shortcodes/quickstart-list.html

1. Renames path of `/quickstarts/node/*` to `/quickstarts/nodejs`
2. Renames "Node" to "Node.js" on `/quickstarts/nodejs`
3. Adds Node.js to `/quickstarts`
4. Fixes exporter error

content: rename Node to Node.js

---

static/css/content.css

This addresses a small nitpick of mine on my original implementation of the exporter cards.
After making the vendor cards with a fixed width, it made it clear that the variable width of the exporter cards causes the overall appearance to look "wrong".
This PR sets a fixed width to exporter cards.

Standardize exporter card width

---

content/quickstart/node.js/_index.md
content/quickstart/node.js/metrics.md
content/quickstart/node.js/tracing.md

Some links were broken after the node.js --> nodejs
rename. However, we had already advertised them,
hence provide those aliases.

content/quickstart: add aliases for node.js --> nodejs

---

content/_index.md
content/community/reporting-issues.md
content/language-support/_index.md
layouts/shortcodes/languages.html

Addresses requests that were sent via a forwarded email:
* Add @tsloughter and @deadtrickster as Erlang owners
* Replaces all references of "Erlang" with "Erlang/Elixir",
except for the headers that show the feature matrix
as "Erlang/Elixir" overflows its column tab.
Fixes #319

content, layouts: add Erlang/Elixir owners

---

content/guides/exporters/supported-exporters/Go/Jaeger.md

Update Jaeger UI port is: `16686`. Port `6831` is Jaeger Agent that accept `jaeger.thrift` over compact thrift protocol
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/census-instrumentation/opencensus-website/321)

Update Jaeger UI endpoint

---

content/guides/exporters/supported-exporters/Go/Stackdriver.md
content/guides/exporters/supported-exporters/Java/SignalFx.md
content/guides/exporters/supported-exporters/Java/Stackdriver.md
content/guides/exporters/supported-exporters/Node.js/stackdriver-stats.md
content/guides/gRPC/Go.md
content/guides/integrations/memcached/Go.md
content/guides/integrations/redis/Go/gomodule_redigo.md

Fixes #314
* Provide an advisory URL to official Stackdriver docs but
also change as many explicit usages of view.ReportingPeriod
with Stackdriver to >=60 seconds
* Also update an erraneous Java import path for the SignalFx
exporter

content/*: add Stackdriver metrics reporting period advisory

---

content/articles/_index.md
content/articles/iot.md
content/blogs/_index.md

Fixes #324
This PR does a few things:
1. Populates `/blogs` with content from the [previous iteration](https://github.com/census-instrumentation/opencensus-website/blob/701f94daaa6358b9551ab2da40298e8e89bf5a24/content/blog.md). It is now an index of blog listings.
2. Adds "Internet of Things" to the blog index. I saw that the file was initially edited on August 9th, so I dated the blog entry as August 9th.
3. Because we have many entries in the blog index, but the menu item `blog` has only one child entry (which is Internet of Things), I have removed the child entry and `blog` is no longer a parent element. Users can still access the "Internet of Things" blog from the blog index page.
Before (regarding 3):
After:

Migrate previous blog content

---

content/articles/iot.md

Add OpenCensus logo to Articles

---

content/_index.md
content/guides/exporters/_index.md
content/guides/exporters/custom-exporter/_index.md
layouts/shortcodes/quickstart-list.html

* Reported offline via direct message, the front page is missing
"Node.js" as a supported language
* Noticed while combing through:
+ supported exporters page is missing Node.js' metrics card
+ custom exporters page uses "Node" as name, it should be Node.js
+ quickstart-list is missing "Metrics" for Node.js
Fixes #332

content: fix Node.js missing and related info

---

content/quickstart/go/tracing.md

Zipkin was misidentified as a "metrics" backend which
is typo since we are in a tracing quickstart and
Zipkin is a "tracing" backend.

quickstart/go/tracing: fix typo in backend type

---

content/quickstart/node.js/metrics.md

Follow-up from #284 -- `import` makes code unrunnable in Node (right now), so this change switches all `import` statements to use `require` instead.

Use require instead of import in Node metrics docs

---

content/core-concepts/metrics.md

- Fix broken markdown under Sampling for linking [1] dropped.

core-concepts/metrics: Fix broken link under Sampling

---

content/quickstart/nodejs/_index.md
content/quickstart/nodejs/metrics.md
content/quickstart/nodejs/tracing.md

The URLs of these pages had been forced
with the Hugo/Markdown meta-tag 'url' hence
the bad doubly included URLs
Topic|Bad relative URL
---|---
Metrics|/quickstart/node.js/quickstart/nodejs/metrics
Tracing|/quickstart/node.js/quickstart/nodejs/tracing
yet they should be
Topic|Good relative URL
---|---
Metrics|/quickstart/nodejs/metrics
Tracing|/quickstart/nodejs/tracing
but also for some reason the `Node.js` directory was ill-named
as `Node.js` instead of like the others being in lower case
and avoiding the `.js` suffix, for which we already have aliases.
This change fixes those problems mentioned above.
Fixes #364

quickstart/node.js: fix buggy Node.js URLs

---

content/quickstart/go/tracing.md

This is a small follow up to https://github.com/census-instrumentation/opencensus-website/issues/368 and its fix https://github.com/census-instrumentation/opencensus-website/pull/369.
This fixes the following formatting issue:

quickstart/go/tracing: fix example code formatting

---

layouts/shortcodes/feature-matrix.html

There should be a space between "T" and "S" for Stackdriver exporters.

content/feature-matrix: add a space between SD trace and stats exporters.

---

content/_index.md

Honeycomb.io is on https://opencensus.io/introduction/ but not on the index page.

content/index: Add Honeycomb.io to index page.

---

content/guides/exporters/supported-exporters/Node.js/Jaeger.md

This fix is necessary because in https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/index.ts#L54 we have 
```
import * as logger from './common/console-logger';
export {logger};
```
this imports the entire console-logger module is imported under the namespace `logger`.  Then we export that.
Therefore, to gain access to this function https://github.com/census-instrumentation/opencensus-node/blob/master/packages/opencensus-core/src/common/console-logger.ts#L109 we end up needing to use `core.logger.logger`.
I'm open to this also being fixed by fixing the export (see https://github.com/census-instrumentation/opencensus-node/pull/146), as it seems a bit unintuitive.

Fix import naming issue in example code

---

layouts/shortcodes/feature-matrix.html

Note that td C# is missing for row Honeycomb.

feature-matrix: add a missing td.

---

content/guides/exporters/custom-exporter/Cpp/Tracing.md
content/guides/exporters/custom-exporter/Cpp/_index.md
content/guides/exporters/custom-exporter/_index.md

Move the trace exporter guide to the right location that is
under "guides/exporters/custom-exporters/cpp"
but also added the necessary "_index.md" and logo entries.

guides/custom-exporter/cpp: relocate trace exporter guide

---

static/css/header.css
themes/docdock/layouts/partials/flex/body-beforecontent.html

Button is added to top-right of header. It opens a link in a new window to the [user survey](https://docs.google.com/forms/d/10ENCVl6qBF6GtOH3tjxqlyktlJo4hz6x9lnbVFvBe24/).
Disappears when browser's width is less than 640px

Add header survey button

---

static/css/header.css

As per offline feedback, the survey button colors have been inverted in an effort to catch the user's eye.
This applies to both desktop and mobile buttons.
New in this PR:
Currently deployed:

Invert survey button colors

---

content/guides/exporters/supported-exporters/Go/_index.md
content/guides/exporters/supported-exporters/Java/_index.md
content/guides/exporters/supported-exporters/Java/stackdriver-stats.md
content/guides/exporters/supported-exporters/Python/_index.md

A bunch of the listings on */supported-exporters/*/_index.md
hard coded listings but that means that if we change or remove
any item, we'll have stale data. Also some URLs were broken.
This change fixes that fragility by using {{% children %}}
to list out available exporters.

content/*/supported-exporters/*: use {{% children %}} listing

---

content/stats/view.md

The /stats/views page really should be /stats/view.
This change fixes that but also adds an alias to /stats/view
of /stats/views
Fixes #419

content/stats: views.md -> view.md

---

content/exporters/supported-exporters/Go/ApplicationInsights.md
content/exporters/supported-exporters/Go/DataDog.md
content/exporters/supported-exporters/Go/Honeycomb.md
content/exporters/supported-exporters/Go/Jaeger.md
content/exporters/supported-exporters/Go/Prometheus.md
content/exporters/supported-exporters/Go/Stackdriver.md
content/exporters/supported-exporters/Go/XRay.md
content/exporters/supported-exporters/Go/Zipkin.md
content/exporters/supported-exporters/Go/_index.md
content/exporters/supported-exporters/Java/Instana.md
content/exporters/supported-exporters/Java/Jaeger.md
content/exporters/supported-exporters/Java/Prometheus.md
content/exporters/supported-exporters/Java/SignalFx.md
content/exporters/supported-exporters/Java/Zipkin.md
content/exporters/supported-exporters/Java/_index.md
content/exporters/supported-exporters/Java/stackdriver-stats.md
content/exporters/supported-exporters/Java/stackdriver-trace.md
content/exporters/supported-exporters/_index.md

Update URL aliases to ensure that the old links are
routed to the proper current location and don't 404
Updates #423

exporters/{Go, Java}: update URL aliases

---

content/exporters/custom-exporter/Cpp/Tracing.md
content/exporters/custom-exporter/Cpp/_index.md
content/exporters/custom-exporter/Go/Metrics.md
content/exporters/custom-exporter/Go/Trace.md
content/exporters/custom-exporter/Go/_index.md
content/exporters/custom-exporter/Java/Trace.md
content/exporters/custom-exporter/Java/_index.md
content/exporters/custom-exporter/Node.js/Metrics.md
content/exporters/custom-exporter/Node.js/Trace.md
content/exporters/custom-exporter/Node.js/_index.md
content/exporters/custom-exporter/_index.md

Added URL aliases for the "How to write a custom exporter"
pages for all the languages and pages underneath.
Updates #423

exporter/custom_exporter/*: add URL aliases

---

content/quickstart/_index.md

Currently the quickstart page links to /metrics, which results in a 404.  This change will link to /stats, which seems to be the appropriate documentation.

Update quickstart page to correctly link to metrics page

---

content/stats/view.md

Currently, the go code snippit in the stats -> view page is missing an import for the opencensus tag package.  This change adds the correct import.

Add missing import for opencensus tag package

---

layouts/shortcodes/languages.html

Replace @liyanhui1228 with @c24t (myself!) as maintainer of the python client library.
@reyang are you still ok with being a "delegate" here?

Replace Angela with Chris

---

layouts/shortcodes/languages.html

Kelvin Jin now works on other projects so instead
add Ievgenii Saikevych who is the primary contact
for OpenCensus-Node.js

community/roadmap/languages: update the Node.js owner

---

content/guides/integrations/google_cloud/google_cloud_spanner/Go.md

Fixed a typo where in the illustratory sections,
grcp
instead of
grpc

guides/spannner: fixed typo grcp to grpc

---

config.toml
themes/docdock/i18n/en.toml
themes/docdock/layouts/partials/flex/body-aftercontent.html

Fixes https://github.com/census-instrumentation/opencensus-website/issues/428
Clicking on that takes to you to an edit page on Github:
Note: Original English text was "Improve this Page" and I changed that to "Edit this page on Github." There are other localizations included that I did not change as I didn't want to provide a false translation.

Add 'Edit this page on Github' link

---

content/exporters/supported-exporters/Go/Prometheus.md

Noticed while reading through that view.RegisterExporter(pe)
was not invoked for the Prometheus tutorial

exporters/*/Go/Prometheus: ensure view.RegisterExporter in tutorial

---

content/quickstart/go/tracing.md
content/quickstart/java/tracing.md
content/quickstart/nodejs/tracing.md
content/quickstart/python/tracing.md

Adds an "all" tab to the "How does it work?" section. The "all" tab includes the entire code reference.

Show all code in new tracing quickstarts

---

content/quickstart/nodejs/metrics.md
content/quickstart/python/metrics.md

Addresses #470
Part 2 of 2 pull request to reduce cognitive load as reviewing quickstarts is no simple task.
This PR does the following for the Node Metrics quickstart:
1. Removes the "error" measure
2. Creates a tag for "status" and "Error"
3. Sets "status" tag to "OK"
4. Added exception handling
5. If error, "status" tag is set to "ERROR" and "error" tag is set to the error string
This PR does the following for the Python Metrics quickstart:
1. Removes the "error" measure
2. Creates a tag for "status" and "Error"
3. Sets "status" tag to "OK"

quickstart/{node, python}/metrics: Add tags for "status" and "error"

---

content/quickstart/go/metrics.md
content/quickstart/java/metrics.md

Addresses #470
Part 1 of 2 pull request to reduce cognitive load as reviewing quickstarts is no simple task.
This PR does the following for Go & Java Metric quickstarts:
1. Removes the "error" measure
2. Creates a tag for "status" and "Error"
3. Sets "status" tag to "OK"
4. If error, "status" tag is set to "ERROR" and "error" tag is set to the error string
5. Wrapped `readEvaluateProcessLine` in a latency measurement to catch errors

quickstart/{java, go}/metrics: Add tags for "status" and "error"

---

content/quickstart/go/metrics.md

It seems that `err` is not declared properly for some of the code snippets. It seems that it was removed in https://github.com/census-instrumentation/opencensus-website/pull/484/ .
Some of the other changes also seemed unnecessary for some functions (like naming the error return value `(terr error)` but not using `terr`). One change that may want to be investigated further is:
https://github.com/census-instrumentation/opencensus-website/pull/484/files#diff-4d73bb710d0b193312291ce07a0b156cL620
where the `log.Fatal(err)` replaces `return err`. The `log.Fatal` will cause a panic and I believe does not work correctly with the intended behavior in line 686 ( https://github.com/census-instrumentation/opencensus-website/pull/484/files#diff-4d73bb710d0b193312291ce07a0b156cL686 ) where any …

Fix missing err short assignment in Go Metrics

---

content/guides/integrations/google_cloud/google_cloud_spanner/Go.md
content/guides/integrations/google_cloud/google_cloud_spanner/Java.md

* The Go package URL was mistakenly
cloud.google.com/spanner
instead of
cloud.google.com/go/spanner
* In the Introduction section for both Go and Java,
the listings were next to the first sentence hence
weren't correctly rendered
* Mention that the metrics are provided by gRPC and OpenCensus

integrations/*/spanner: fix Go package URL, lists

---

content/quickstart/nodejs/metrics.md

Thanks to a nice catch by @odeke-em, this PR prevents a possible double-measurement from happening.

content/quickstarts/node/metrics: Extract latency measurement outside of try/catch

---

layouts/shortcodes/feature-matrix.html

fixing typo "pyton" => "python"

"pyton" => "python"

---

content/guides/integrations/mongodb/go_driver.md

Fix broken links in the Go driver integration guide. 
@odeke-em

Guides/integrations/Go driver: Fix broken links

---

content/guides/integrations/redis/Java.md

The Jedis wrapper's version for io.orijtech.integrations/ocjedis
is now at 0.0.3 for compatibility with the latest Jedis version 3.0.1.
This change also adds a section "Dependency listing" which
provides a quick link for adding:
* Maven
* Gradle
* Ivy
* Buildr
dependencies of the wrapper.

integrations/redis/Jedis: update version to 0.0.3

---

content/guides/integrations/sql/java_sql.md

Update the JDBC integration path from
"io.opencensus.integration.ocjdbc"
to
"io.orijtech.integrations.ocjdbc"
because the old publishing was a little bureaucratic
and stalled for more than 3 months; publishing it
under "io.orijtech.integrations.ocjdbc" is just a flexible
way for maintaining the integration but also for putting
it into the hands of users without quarter long stalls.
Fixes #527
Retrofit by https://github.com/orijtech/opencensus-java-jdbc/pull/1

integrations/sql: update JDBC import path

---

content/guides/integrations/sql/java_sql.md

Retouch the OCJDBC integration guide now that it was successfully
published on Sonatype. This retouch ensures that the end-to-end
example fully compiles. The last edits of the actual integration
introduced an unexpected compulsory option which rendered the
previous guide uncompilable.
This change also involved running `./gradlew goJF` to format
the Java source code.
Updates #527

integrations/sql: retouch ocjdbc to ensure working end-to-end

---

content/guides/integrations/google_cloud/google_cloud_spanner/Java.md

Reported offline by Alex Amies, the Google Cloud Spanner integration
guide was outdated but also couldn't compile.
This change modernizes the guide to use OpenCensus-Java 0.18.0
(the lastest) up from 0.11.0 and the Cloud Spanner Java
dependency to 1.5.0, up from 0.33.0-beta
Also ensuring that the guides run/compile successfully/end-to-end.
This change also ran `./gradlew goJF` on the Java source code
as well as followed Alex's recommendation of removing usages
of "this.*" except when dealing with scoping problems, as that style
is the norm in Java.
Supersedes #540

guides/google_cloud_spanner: update dependencies + ensure compilation

---

layouts/shortcodes/quickstart-list.html

The C# logo and shortcut to quickstarts was missing
on the "Quickstart" landing page.
/cc @simonz130

quickstart: add C# on listing

---

content/exporters/supported-exporters/Go/DataDog.md

This change specifies the need for setting `AlwaysSample` when using the
Datadog exporter, in order to get accurate APM metrics (and sampling)
within the Datadog product.

content/exporters: update Datadog Go exporter example

---

content/guides/http/_index.md

I noticed that there is no HTTP Java integration on the web site Integration Guide page. I think that we could improve that, at least by adding the links to the page with the Java contrib code examples here
https://github.com/census-instrumentation/opencensus-java/tree/master/examples#to-run-http-server-and-client
The existing links at the bottom of the page do not make sense. One goes to a generic page at Mozilla and one goes to the IETF standard for HTTP. This PR replaces them with links to the Go and Java API resources.

Added links to Go and Java APIs

---

content/tag/_index.md
content/tag/key.md
content/tag/map.md
content/tag/serialization.md
content/tag/value.md

Current link to specs/TagContext are wrong due to a renaming of TagContext.md into TagMap.md

Fix 404 on TagContext spec

---

content/stats/view.md

This change fix a typo mistake in view python example.

Fix typo in view python example

---

content/exporters/supported-exporters/Python/ApplicationInsights.md
content/exporters/supported-exporters/Python/Stackdriver.md
content/guides/gRPC/Python.md
content/integrations/memcached/Python.md

Replace references to `BackgroundThreadTransport` with `AsyncTransport` to match https://github.com/census-instrumentation/opencensus-python/pull/452.

Update python docs for new transport name

---

content/exporters/custom-exporter/Node.js/Metrics.md
content/exporters/custom-exporter/Node.js/Trace.md
content/exporters/supported-exporters/Node.js/Instana.md
content/exporters/supported-exporters/Node.js/Jaeger.md
content/exporters/supported-exporters/Node.js/Prometheus.md
content/exporters/supported-exporters/Node.js/Zipkin.md
content/exporters/supported-exporters/Node.js/stackdriver-stats.md
content/exporters/supported-exporters/Node.js/stackdriver-trace.md
content/quickstart/nodejs/metrics.md
content/stats/measure.md
content/stats/view.md
content/tag/key.md
content/tag/map.md
content/tag/value.md

This PR contains the following changes.
1. [Node.js 0.0.9 version](https://github.com/census-instrumentation/opencensus-node/pull/341) has introduced butch of changes for Stats (Metrics) examples including TagKey, TagValue and TagMap. 
2. Change ```var``` -> ```const```.
3. Fixes #355 ->  use the open source exporter (Prometheus) for quickstart  tutorials.

Node.js: Update examples

---

content/agent/exporters/stackdriver/metrics.md
content/agent/exporters/stackdriver/tracing.md

Some copy+paste remnants from the Stackdriver metrics
exporter page.

agent/exporters: remove metrics vestiges from traces page

---

content/integrations/sql/java_sql.md

After @rowdyrabbit's fix in
https://github.com/census-ecosystem/opencensus-java-jdbc/pull/57
follow suit and update the guides to reflect published
update with version 0.0.3.

content/integrations: update to v0.0.3

---

content/exporters/custom-exporter/_index.md

C++ does not have a guide on stats exporters and Java does

Update index page for custom-exporters

---

content/integrations/google_cloud/google_cloud_storage/Go.md

Fixed a statement that implied that the GCS client necessarily uses HTTP. GCS can use HTTP but does not necessarily use it.
Fixed two couple of typos where Spanner was mentioned but GCS was intended.

Fixed a minor factual error that GCS may use instead of GCS uses, typos

---

content/exporters/supported-exporters/Go/DataDog.md

I think, sd variable copied from another code by mistake. The build is taking error:
./main.go:20:25: undefined: sd
The variable should be dd.

Fix undefined variable in the example code.

---

content/exporters/supported-exporters/Python/Honeycomb.md

The Python exporter for Honeycomb is available [here](https://github.com/codeboten/ochoneycomb)
Signed-off-by: Alex Boten <alrex.boten@gmail.com>

Adding Honeycomb Python exporter

---

content/exporters/supported-exporters/Go/Jaeger.md
content/exporters/supported-exporters/Java/Jaeger.md

Reported by @bzon:
> the Jaeger collector endpoint address in this documentation is wrong https://opencensus.io/exporters/supported-exporters/go/jaeger/.
> It should just be http://localhost:14268 and not http://localhost:14268/api/traces. I used the all-in-one docker image of jaeger when following the guide.

content/exporters: update Jaeger endpoint.

---

content/tag/value.md

The example previously had an import only. Add an example in the same vein as the Java example.

Update tag value documentation Python example.

---

content/tag/value.md

Just realized after submitting the other pull request that the import is incorrect :)

Fix import typo for Python TagValue example.

---

content/exporters/supported-exporters/Python/ApplicationInsights.md
content/exporters/supported-exporters/Python/Honeycomb.md
content/exporters/supported-exporters/Python/Jaeger.md
content/exporters/supported-exporters/Python/Stackdriver.md
content/exporters/supported-exporters/Python/Zipkin.md

This PR updates the python examples to reflect the [move to separate exporter packages](https://github.com/census-instrumentation/opencensus-python/pull/550), and does some incidental cleanup.
Fixes #664.

Update python examples for exporter package move

---

content/exporters/custom-exporter/Go/Metrics.md

The existing page at 
https://opencensus.io/exporters/custom-exporter/go/metrics/
leads to a 404

Fixed broken link to supported exported

---

content/guides/http/go/net_http/server.md

Added Zipkin imports and export initialization to example for for Go HTTP server example, as per issue
https://github.com/census-instrumentation/opencensus-website/issues/677

Fix for #677 Add Zipkin to Go HTTP server example code

---

content/quickstart/python/tracing.md

Zipkin Exporter is now part of the opencensus-ext-zipkin package, https://opencensus.io/exporters/supported-exporters/python/zipkin/
A PR has also been filed against `opencensus-quickstarts` repo to fix this change as well.
https://github.com/opencensus-otherwork/opencensus-quickstarts/pull/1

quickstart/tracing/python: use new import paths

---

content/service/exporters/wavefront/_index.md

Add content for oc-service Wavefront exporter.
Angle brackets weren't added to port numbers because it is messing up syntax highlighting.
Closes #687 
/cc @songy23

service/exporters: Add Wavefront content

---

content/integrations/sql/java_sql.md

Following suit with:
* https://github.com/census-ecosystem/opencensus-java-jdbc/pull/59
* https://github.com/orijtech/opencensus-java-jdbc/pull/1
initiated by @dmichel1
Upgrade to updated ocjdbc version v0.0.4 which
also uses OpenCensus-Java v0.21.0 having taken
in a bug fix in OpenCensus v0.18.0 that reduced
high CPU usage for low QPS services.

integrations/ocjdbc: upgrade to v0.0.4

---

content/service/components/agent/_index.md

- Fixes a typo. 
- Uppercases a word at the beginning of a sentence.
- Could change `various exporter` to `various exporters` instead of just `exporter` as suggested in this PR.

Fix typos and uppercasing

---

content/quickstart/python/metrics.md

In current example for [OpenCensus Stats for Python](https://opencensus.io/quickstart/python/metrics/) calls `opencensus.stats.Stats()` but [it is made private in latest implementation](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/stats/stats.py) and it's encouraged to use `opencensus.stats.stats` instance.
This pull request change the example code to follow the latest API of OpenCensus Stats for Python.

change stats.Stats() to stats.stats

---

content/guides/http/go/net_http/server.md

Instrumented was spelled wrong. @reyang spotted the typo in my PR using this code. I fixed it.

Fix typo on server.md

---

content/exporters/supported-exporters/Go/Prometheus.md
content/exporters/supported-exporters/Go/Stackdriver.md
content/guides/gRPC/Go.md
content/guides/http/go/net_http/client.md
content/integrations/google_cloud/google_cloud_spanner/Go.md
content/integrations/google_cloud/google_cloud_storage/Go.md
content/integrations/redis/Go/gomodule_redigo.md
content/integrations/sql/go_sql.md
content/quickstart/go/metrics.md

- for prometheus just remove the registration.
updates https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/188#issuecomment-526456067

replace exporter registration with start/stop for stackdriver exp.

---

content/integrations/sql/java_sql.md

After @marcusb's PR that adds tracing javax.sql.DataSource
in https://github.com/orijtech/opencensus-java-jdbc/pull/2,
we've published an update to ocjdbc and this just bumps
up the version of the published ocjdbc integration to
v0.0.5 but also its dependency opencensus-java to v0.24.0.

integrations/sql: update java/ocjdbc to v0.0.5

---

.travis.yml

Firebase seems to require a version of
Node.js >=8.0 as per the silent failure in
https://travis-ci.org/census-instrumentation/opencensus-website/builds/580447164
```shell
Firebase CLI v7.3.0 is incompatible with Node.js v7.10.1
Please upgrade Node.js to version >= 8.0.0
```
Fixes #713.

.travis.yml: upgrade to Node.js 8

---

content/exporters/supported-exporters/Go/DataDog.md

I appreciate easy-to-understand documents.
Go language differentiates the case in package PATH. the correct `opencensus-go-exporter-datadog` repository PATH on GitHub is below.
https://github.com/DataDog/opencensus-go-exporter-datadog
But, it import path in sample codes is below:
https://opencensus.io/exporters/supported-exporters/go/datadog/
```go
package main
import (
"log"
"github.com/Datadog/opencensus-go-exporter-datadog"
"go.opencensus.io/stats/view"
)
func main() {
dd, err := datadog.NewExporter(datadog.Options{})
if err != nil {
log.Fatalf("Failed to create the Datadog exporter: %v", err)
}
// It is imperative to invoke flush before your main function exits
defer dd.Stop()
// Register it as a metrics exporter
view.RegisterExporter(dd)
}
```
`Data"d"og` is not correct, the correct …

sample code: Fix import package name

---

.gitignore
content/exporters/supported-exporters/Python/DataDog.md
layouts/shortcodes/feature-matrix.html

Follow-up of https://github.com/census-instrumentation/opencensus-python/pull/793 and https://github.com/census-instrumentation/opencensus-python/pull/799, I found that the Datadog exporter for traces in Python doesn't appear to be supported on the opencensus.io website when it's in fact supported.
Example 1: missing datadog
Example 2: missing "T" in the Python/Datadog intersection

Documentation: Python trace exporter to Datadog is supported

---

content/quickstart/python/metrics.md

To export metrics `opencensus-ext-prometheus` python package needs to be installed. And a different package needs to be imported in the code to export to prometheus.

Update metrics.md for OC python

---

content/service/components/agent/_index.md
content/service/receivers/opencensus/_index.md

Use "grpc-gateway" phrasing to avoid confusion between
the JSON gateway and the grpc-web protocol.

Update grpc-gateway references

---

content/guides/gRPC/Go.md

`grpc.WithStatsHandler(new(ocgrpc.ClientHandler))` and `grpc.StatsHandler(&ocgrpc.ServerHandler{})` were omitted for tracing example on the client and the server ( they were only present on metrics and combined )

improved documentation for gRPC opencensus tracing example

---

content/guides/gRPC/Java.md

The instructions for including OpenCensus tracing in gRPC-java use an older version of gRPC which predates the refactor to pull OpenCensus instrumentation code into a separate artifact (https://github.com/grpc/grpc-java/commit/b7ccc0d14297f255557e67a4f0364480f4a80bcf)
Update this tutorial to use newer versions of gRPC and OpenCensus

Update Java gRPC instructions to include grpc-census

---

content/zpages/java.md

fix typo in zpages - should be "statsz" instead of "statz"

fixing typo in zpages

---

content/quickstart/go/metrics.md

"startTime" declaration was missing in function readEvaluateProcess,
causes the quickstart code snippet fails to run.

content/quickstart/go: fix missing code snippet

---

content/quickstart/go/tracing.md

content/quickstart/go: fix invalid import path

---

content/service/components/collector/_index.md

The hyperlinks to the 'Receiver' and 'Exporter' pages currently result in a 404. This change simply seeks to update these links to point to (what I assume are) the relevant pages.

Fix broken links to Receivers & Exporters

---

content/_index.md

A couple of customers have been confused with the status of OpenTelemetry. From the main page, they perceived that OpenTelemetry is already a production ready set of libraries (GA/stable), which is not the case.
Changes the tense to "will" to reflect current status of OpenTelemetry project. Also adds a link to the blog to direct users to progress.

Change title card on main page
